Fix #301, Add Github workflows to bootes.x
nasa/cFS pull request #324
Opened 2021-08-02 16:35 UTC by Frank393

**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [ ] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Redo of pull request #305 
- Added workflow directory and Codeql files for the Bootes build to fixes #301  .
- Modified  build-documentation.yml and static-analysis.yml to work with Bootes build.

**Testing performed**
Steps taken to test the contribution:
1. Modified path for the build-documentation.yml build OSAL Guide so it could find the correct directory.
Documentation workflow [run](https://github.com/Frank393/cFS/actions/runs/1037623337)
2.  Modified path for the static-analysis.yml cfe strict cppcheck to find the correct directory.
Static analysis workflow [run](https://github.com/Frank393/cFS/actions/runs/1037623341)

**Expected behavior changes**

- With the added workflow and Codeql we can test the previous build with GitHub action and Codeql semantic code analyzer.

**System(s) tested on**
 - GitHub actions ubuntu-18.04 runner

**Contributor Info - All information REQUIRED for consideration of pull request**
Frank I. Gonzalez Soto , GSFC Code 582 intern

2021-08-04 13:31 UTC, astrogeco requested changes
Change the pull_request trigger to only focus on bootes.x branch. 

Change all checkout actions to checkout bootes branch instead of main

2021-08-04 13:31 UTC, astrogeco commented on .github/workflows/build-cfs-deprecated.yml
> +        with:
This should checkout the bootes branch instead of main

2021-08-04 13:54 UTC, skliper commented on .github/workflows/build-cfs-deprecated.yml
> +  pull_request:
I don't follow why you'd need to specify... if the workflow is specific to the bootes.x branch already it's only going to run within that context?  It'd only be needed if you merged this workflow to other branches but only wanted to run it in certain cases... as it is you want to run it for any branch it's in right?

2021-08-04 14:11 UTC, astrogeco commented on .github/workflows/build-cfs-deprecated.yml
> +  pull_request:
I think you're right, I was wondering if maybe for the pull_request one? Especially if we change the checkout action to target bootes

2021-08-04 14:23 UTC, skliper commented on .github/workflows/build-cfs-deprecated.yml
> +  pull_request:
But wouldn't the workflow still only be in PR's that are applicable?  I haven't been able to think of a case where you wouldn't want to run the workflow (based on target branch or whatever) if it's in your branch.

2021-08-04 16:04 UTC, astrogeco commented
[CCB:2021-08-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-04-2021) APPROVED

2021-08-24 13:44 UTC, astrogeco approved these changes

2021-08-24 13:44 UTC, merged